#!/usr/bin/env python3
"""Run the existing strict Japanese translation pipeline with LFM2.5.

The core translation code is model-agnostic but historically named after Qwen.
This wrapper switches runtime metadata and invalidates the old summary-format
cache so existing articles can be gradually regenerated by LFM2.5.
"""

import translate_news_llm as engine
import strict_qwen_translate as strict

MODEL_ID = "LiquidAI/LFM2.5-8B-A1B-GGUF"
MODEL_VARIANT = "Q4_K_M"
MODEL_REVISION = "lfm2.5-8b-a1b-q4-k-m-summary-facts-region-titles-strict-ja-v1"
SUMMARY_FORMAT_VERSION = 3


def configure_lfm() -> None:
    engine.MODEL_ID = MODEL_ID
    engine.MODEL_VARIANT = MODEL_VARIANT
    engine.MODEL_REVISION = MODEL_REVISION
    engine.SUMMARY_FORMAT_VERSION = SUMMARY_FORMAT_VERSION
    strict.STRICT_MODEL_REVISION = MODEL_REVISION


def main() -> int:
    configure_lfm()
    return strict.main()


if __name__ == "__main__":
    raise SystemExit(main())
